// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsQSi4Lo032b1IloAZtqbsOlev2-uZyuo',
    appId: '1:746454660579:web:5a51dbdc811ebbb5d21cd6',
    messagingSenderId: '746454660579',
    projectId: 'coding-minds3',
    authDomain: 'coding-minds3.firebaseapp.com',
    databaseURL: 'https://coding-minds3-default-rtdb.firebaseio.com',
    storageBucket: 'coding-minds3.appspot.com',
    measurementId: 'G-BQV1Y0R4JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoD9g2N_SIGEiZIg-rssrsG0s4amyZUdc',
    appId: '1:746454660579:android:04a351dc40f88acbd21cd6',
    messagingSenderId: '746454660579',
    projectId: 'coding-minds3',
    databaseURL: 'https://coding-minds3-default-rtdb.firebaseio.com',
    storageBucket: 'coding-minds3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEib2V9bwVzScm5_dDxoZ_0V7nlwOk-4',
    appId: '1:746454660579:ios:dc347b22d3629dc6d21cd6',
    messagingSenderId: '746454660579',
    projectId: 'coding-minds3',
    databaseURL: 'https://coding-minds3-default-rtdb.firebaseio.com',
    storageBucket: 'coding-minds3.appspot.com',
    iosClientId: '746454660579-54jfkphpadgi8qaf15gkrp27r30ftefc.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingMindsBootstrap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEib2V9bwVzScm5_dDxoZ_0V7nlwOk-4',
    appId: '1:746454660579:ios:dc347b22d3629dc6d21cd6',
    messagingSenderId: '746454660579',
    projectId: 'coding-minds3',
    databaseURL: 'https://coding-minds3-default-rtdb.firebaseio.com',
    storageBucket: 'coding-minds3.appspot.com',
    iosClientId: '746454660579-54jfkphpadgi8qaf15gkrp27r30ftefc.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingMindsBootstrap',
  );
}
